import { useEffect, useState } from 'react';
import { getTaxSummary, getBusinessTaxSummary } from '../../services/api';
import Card from '../../components/common/Card';
import Button from '../../components/common/Button';
import StatCard from '../../components/common/StatCard';
import styles from './TaxForms.module.css';

const CURRENT_YEAR = new Date().getFullYear();

function generateOwnerTaxHTML(owner, year) {
  const paymentRows = owner.payments.map((p) =>
    `<tr><td>${p.month}</td><td>${p.property}</td><td>$${p.amount.toLocaleString()}</td><td>${p.paidOn}</td></tr>`
  ).join('');

  return `<!DOCTYPE html><html><head><title>Tax Form - ${owner.owner} - ${year}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 40px; color: #111; }
    .header { border-bottom: 3px solid #2563eb; padding-bottom: 20px; margin-bottom: 32px; }
    .company { font-size: 24px; font-weight: bold; color: #2563eb; }
    .form-title { font-size: 20px; font-weight: bold; margin: 8px 0; color: #374151; }
    .form-subtitle { color: #6b7280; font-size: 14px; }
    .section { margin-bottom: 28px; }
    .section-title { font-size: 16px; font-weight: bold; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f3f4f6; text-align: left; padding: 10px 12px; font-size: 12px; color: #6b7280; text-transform: uppercase; }
    td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
    .total { font-size: 20px; font-weight: bold; color: #111; margin-top: 8px; }
    .footer { margin-top: 48px; border-top: 1px solid #e5e7eb; padding-top: 20px; font-size: 12px; color: #9ca3af; text-align: center; }
    .disclaimer { background: #fef3c7; border: 1px solid #fde68a; padding: 12px; border-radius: 8px; margin-top: 24px; font-size: 12px; color: #92400e; }
  </style></head><body>
  <div class="header">
    <div class="company">🏢 PropMgmt</div>
    <div class="form-title">Annual Rental Income Statement</div>
    <div class="form-subtitle">Tax Year ${year} · Owner Copy (Form 1099-MISC Reference)</div>
  </div>
  <div class="section">
    <div class="section-title">Owner Information</div>
    <table><tr><th>Field</th><th>Value</th></tr>
    <tr><td>Owner Name / Entity</td><td>${owner.owner}</td></tr>
    <tr><td>Number of Properties</td><td>${owner.propertyCount}</td></tr>
    <tr><td>Properties</td><td>${owner.properties.join(', ')}</td></tr>
    <tr><td>Tax Year</td><td>${year}</td></tr>
    </table>
  </div>
  <div class="section">
    <div class="section-title">Payment Details</div>
    <table><thead><tr><th>Period</th><th>Property</th><th>Amount</th><th>Date</th></tr></thead>
    <tbody>${paymentRows}</tbody></table>
  </div>
  <div class="section">
    <div class="section-title">Summary</div>
    <div class="total">Total Gross Rental Income: $${owner.totalRent.toLocaleString()}</div>
  </div>
  <div class="disclaimer">⚠️ This document is for reference purposes only and does not constitute an official tax form. Please consult a qualified tax professional for official tax filings.</div>
  <div class="footer">Generated by PropMgmt Portal · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </body></html>`;
}

function generateBusinessTaxHTML(summary) {
  return `<!DOCTYPE html><html><head><title>Business Tax Summary ${summary.year}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 40px; color: #111; }
    .header { border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 32px; }
    .company { font-size: 24px; font-weight: bold; color: #7c3aed; }
    .form-title { font-size: 20px; font-weight: bold; margin: 8px 0; color: #374151; }
    .section { margin-bottom: 28px; }
    .section-title { font-size: 16px; font-weight: bold; color: #374151; border-bottom: 1px solid #e5e7eb; padding-bottom: 8px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #f3f4f6; text-align: left; padding: 10px 12px; font-size: 12px; color: #6b7280; text-transform: uppercase; }
    td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; }
    .highlight { font-size: 18px; font-weight: bold; color: #7c3aed; }
    .footer { margin-top: 48px; border-top: 1px solid #e5e7eb; padding-top: 20px; font-size: 12px; color: #9ca3af; text-align: center; }
    .disclaimer { background: #fef3c7; border: 1px solid #fde68a; padding: 12px; border-radius: 8px; margin-top: 24px; font-size: 12px; color: #92400e; }
  </style></head><body>
  <div class="header">
    <div class="company">🏢 PropMgmt</div>
    <div class="form-title">Business Annual Tax Summary</div>
    <div class="form-subtitle">Tax Year ${summary.year} · Property Management Company</div>
  </div>
  <div class="section">
    <div class="section-title">Business Summary</div>
    <table><tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Gross Revenue</td><td class="highlight">$${summary.totalRevenue.toLocaleString()}</td></tr>
    <tr><td>Management Fees (10%)</td><td>$${summary.managementFees.toLocaleString()}</td></tr>
    <tr><td>Total Payments Collected</td><td>${summary.totalPayments}</td></tr>
    <tr><td>Active Properties</td><td>${summary.activeProperties} of ${summary.totalProperties}</td></tr>
    <tr><td>Tax Year</td><td>${summary.year}</td></tr>
    </table>
  </div>
  <div class="disclaimer">⚠️ This document is for reference purposes only. Consult a qualified tax professional for official filings.</div>
  <div class="footer">Generated by PropMgmt Portal · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
  </body></html>`;
}

function downloadHTML(html, filename) {
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export default function TaxForms() {
  const [year, setYear] = useState(CURRENT_YEAR);
  const [ownerSummaries, setOwnerSummaries] = useState([]);
  const [businessSummary, setBusinessSummary] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setLoading(true); // eslint-disable-line react-hooks/set-state-in-effect
    Promise.all([getTaxSummary(year), getBusinessTaxSummary(year)])
      .then(([owners, biz]) => {
        if (!cancelled) {
          setOwnerSummaries(owners);
          setBusinessSummary(biz);
        }
      })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [year]);

  if (loading) return <p className={styles.loading}>Loading tax data…</p>;

  return (
    <div>
      <div className={styles.pageHeader}>
        <div>
          <h1 className={styles.title}>Tax Forms</h1>
          <p className={styles.subtitle}>Generate and download tax documents for owners and the business</p>
        </div>
        <div className={styles.yearSelector}>
          <label className={styles.yearLabel}>Tax Year:</label>
          <select
            className={styles.yearSelect}
            value={year}
            onChange={(e) => setYear(Number(e.target.value))}
          >
            {[CURRENT_YEAR, CURRENT_YEAR - 1, CURRENT_YEAR - 2].map((y) => (
              <option key={y} value={y}>{y}</option>
            ))}
          </select>
        </div>
      </div>

      {businessSummary && (
        <Card
          title="Business Tax Summary"
          subtitle={`Property Management Company · Tax Year ${year}`}
          action={
            <Button variant="primary" size="sm" onClick={() => downloadHTML(generateBusinessTaxHTML(businessSummary), `business-tax-${year}.html`)}>
              ⬇️ Download
            </Button>
          }
        >
          <div className={styles.bizStats}>
            <StatCard label="Gross Revenue" value={`$${businessSummary.totalRevenue.toLocaleString()}`} icon="💼" variant="success" />
            <StatCard label="Management Fees" value={`$${businessSummary.managementFees.toLocaleString()}`} icon="💰" variant="primary" />
            <StatCard label="Payments Collected" value={businessSummary.totalPayments} icon="📋" />
            <StatCard label="Active Properties" value={`${businessSummary.activeProperties}/${businessSummary.totalProperties}`} icon="🏘️" />
          </div>
        </Card>
      )}

      <div className={styles.ownersSection}>
        <h2 className={styles.sectionTitle}>Owner Tax Forms</h2>
        <p className={styles.sectionSubtitle}>Individual rental income statements for each property owner</p>
        {ownerSummaries.length === 0 ? (
          <Card><p className={styles.empty}>No owner data found for {year}.</p></Card>
        ) : (
          <div className={styles.ownersGrid}>
            {ownerSummaries.map((owner) => (
              <Card
                key={owner.owner}
                title={owner.owner}
                subtitle={`${owner.propertyCount} propert${owner.propertyCount === 1 ? 'y' : 'ies'}`}
                action={
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => downloadHTML(generateOwnerTaxHTML(owner, year), `owner-tax-${owner.owner.replace(/\s+/g, '-')}-${year}.html`)}
                  >
                    ⬇️ Download
                  </Button>
                }
              >
                <div className={styles.ownerDetails}>
                  <div className={styles.ownerRow}>
                    <span>Total Gross Income</span>
                    <strong className={styles.totalAmount}>${owner.totalRent.toLocaleString()}</strong>
                  </div>
                  <div className={styles.ownerRow}>
                    <span>Payments</span>
                    <span>{owner.payments.length}</span>
                  </div>
                  <div className={styles.propertiesList}>
                    {owner.properties.map((p) => (
                      <span key={p} className={styles.propTag}>📍 {p}</span>
                    ))}
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
